<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../application/models/Comments.php';

/**
 * Test class for Application_Model_Comments.
 * Generated by PHPUnit on 2010-02-23 at 14:57:05.
 */
class Application_Model_CommentsTest extends Zend_Test_PHPUnit_DatabaseTestCase {
    private $_connectionMock;

    protected function getConnection()
    {
        if($this->_connectionMock == null) {
            $connection = Zend_Db::factory('PDO_SQLITE', array('dbname'=>APPLICATION_PATH.'/../data/db/manuscript-testing.db'));
            $this->_connectionMock = $this->createZendDbConnection($connection, 'zfunittests');
            Zend_Db_Table_Abstract::setDefaultAdapter($connection);
        }

        return $this->_connectionMock;
    }

    protected function getDataSet()
    {
        return $this->createFlatXmlDataSet(dirname(__FILE__).'/_files/commentsSeed.xml');
    }

    /**
     * Inserts a comment into the database
     */
    public function testAdd() {
        $data   = array(
            'fileId'    => 1,
            'version'   => 1,
            'comment'   => 'New Comment',
            'author'    => 2,
        );

        $comments   = new Application_Model_Comments();
        $id         = $comments->add($data);
        $comment    = $comments->find($id);

        $this->assertEquals($id, $comment->id);
        $this->assertEquals($data['fileId'], $comment->fileId);
        $this->assertEquals($data['version'], $comment->version);
        $this->assertEquals($data['comment'], $comment->comment);
        $this->assertEquals($data['author'], $comment->author);
    }

    /**
     * Returns all the comments in the system
     */
    public function testFetchAll() {
        $comments   = new Application_Model_Comments();
        $result     = $comments->fetchAll();

        $this->assertEquals(1, count($result));
    }

    /**
     * Returns the backend table
     */
    public function testGetDbTable() {
        $comments   = new Application_Model_Comments();

        $this->assertType('Zend_Db_Table_Abstract', $comments->getDbTable());
    }

    /**
     * Sets the backend table
     */
    public function testSetDbTable() {
        $comments  = new Application_Model_Comments();
        $comments->setDbTable('Application_Model_DbTable_Comments');

        $this->assertType('Application_Model_DbTable_Comments', $comments->getDbTable());
    }
}
?>
