<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../../../application/modules/admin/forms/User.php';

/**
 * Test class for Admin_Form_User.
 * Generated by PHPUnit on 2010-02-28 at 13:33:12.
 */
class Admin_Form_UserTest extends PHPUnit_Framework_TestCase {
    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        $form = new Admin_Form_User();
        $elements    = $form->getElements();

        $this->assertEquals(count($elements), 7);
    }

    /**
     * @todo Implement testIsValid().
     */
    public function testIsValid() {
        $data   = array(
            'username'  => 'myuser',
            'password'  => 'mypass',
            'confPassword'  => 'mypass',
            'name'          => 'My User',
            'email'         => 'myuser@email.com',
            'primaryGroup'  => 1,
        );

        $form   = new Admin_Form_User();

        $this->assertTrue($form->isValid($data));
    }

    public function testFilteredData()
    {
        $data   = array(
            'username'  => 'myuser',
            'password'  => 'mypass',
            'confPassword'  => 'mypass',
            'name'          => 'My User',
            'email'         => 'myuser@email.com',
            'primaryGroup'  => 1,
        );

        $form   = new Admin_Form_User();
        $form->populate($data);

        $this->assertEquals($data, $form->getValues());
    }
}
?>
