<h1>Database Upgrade</h1>

Manuscript has detected that you require a database upgrade. Here is what we're going to do:

<ul>
    <li>Determine what version your database is at</li>
    <li>Determine what version Manuscript needs</li>
    <li>Run all of the needed update scripts, one by one</li>
</ul>

<p>
Manuscript will do its best to make sure that nothing goes wrong and will only be altering the database. Even in the event of a major database corruption, your documents will be left alone.

<p>
<b>Please make sure that you have made a backup before you begin, just in case.</b>

<p>
<form method="post">
    <input type="submit" value="Begin Upgrade">
</post>
