<tr>
	<td><a href="<?php echo $this->baseUrl(); ?>/files/info/file/<?php echo $this->id; ?>"><?php echo $this->title; ?></a></td>
	<td><?php echo $this->mimetype($this->mimetype); ?></td>
	<td align=right><?php echo $this->dateUploaded; ?></td>
	<td align=center><?php echo $this->revision; ?></td>
	<td align=center><a href="<?php echo $this->baseUrl(); ?>/files/view/file/<?php echo $this->id; ?>" target="_new">View</a> : <a href="<?php echo $this->baseUrl(); ?>/files/download/file/<?php echo $this->id; ?>">Download</a></td>
</tr>
