<script type="text/javascript">
    $(document).ready(function() {
        $('#dbType').change(function() {
           $('#sqlServerOptions').hide();
           $('#sqlOptions').hide();
           $('#installButton').hide();

            switch($('#dbType').val()) {
                case 'sqlite':
                    $('#sqlOptions').fadeIn();
                    $('#installButton').fadeIn();
                    break;
                case 'sqlserver2k8':
                    $('#sqlServerOptions').fadeIn();
                    $('#installButton').fadeIn();
                    break;
            }
        });
    });
</script>

<h1>Manuscript Installation</h1>

Congrats! If you've made it this far you seem to have the base install of
Manuscript all set up. All we need to do is gather some database-specific
information so that we can get everything all set.

<form method="post">
<h2>Database</h2>
Manuscript supports SQLite3 and Microsoft SQL Server 2008. Which one do you want
to use?

<?php echo $this->form->getElement('dbType'); ?>

<div id="sqlOptions" style="display: none">
    <h2>SQLite Options</h2>
    There are none! The system will automatically build the database and fill it with the needed data.
</div>

<div id="sqlServerOptions" style="display: none">
    <h2>SQL Server 2008 Options</h2>
    <?php echo $this->form->getElement('host'); ?>
    <?php echo $this->form->getElement('username'); ?>
    <?php echo $this->form->getElement('password'); ?>
    <?php echo $this->form->getElement('dbname'); ?>
</div>

<div id="installButton" style="display: none">
    <h2>Install!</h2>
    We have everything we need. Click the button below and if all goes well you'll be able to log in!
    <?php echo $this->form->getElement('install'); ?>
</div>

</form>

