<tr>
	<td><a href="<?php echo $this->baseUrl(); ?>/files/info/file/<?php echo $this->reference; ?>"><?php echo $this->title; ?></a></td>
	<td><?php echo $this->mimetype; ?></td>
	<td align=right><?php echo $this->dateUploaded; ?></td>
	<td align=center><?php echo $this->version; ?></td>
	<td align=center><a href="<?php echo $this->baseUrl(); ?>/files/view/file/<?php echo $this->reference; ?>" target="_new">View</a> : <a href="<?php echo $this->baseUrl(); ?>/files/download/file/<?php echo $this->reference; ?>">Download</a></td>
</tr>
