<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <?php
        $this->headTitle()->prepend('Manuscript');
        $this->headTitle()->setSeparator(' :: ');
        print $this->headTitle();
    ?>

    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/reset-fonts-grids.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/base-min.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/manuscript.css" type="text/css" />

</head>
<body>
<div id="doc3" class="yui-t1">
    <div id="hd">
        <div id="hd-links">
            <a href="<?php echo $this->baseUrl(); ?>/admin"><span>Admin</span></a> | 
            <a href="<?php echo $this->baseUrl(); ?>/auth/index/logout"><span>Log Out</span></a>
        </div>

        <h1>Manuscript</h1>
    </div>
    <div id="main-nav">
        <div id="main-nav-links">
            <ul>
                <li><a href="<?php echo $this->baseUrl(); ?>/"><span>Home</span></a></li>
                <li><a href="<?php echo $this->baseUrl(); ?>/files"><span>Files</span></a></li>
                <li></li>
            </ul>
        </div>

        <div id="main-nav-search">
            <form method="post" class="searchform" action="<?php echo $this->baseUrl(); ?>/search">
                <p><input type="text" name="search_query" class="textbox" />
                <input type="submit" name="search" class="button" value="Search" /></p>
            </form>
        </div>
    </div>
    <div id="bd">
        <div id="yui-main">
            <div class="yui-b">
                <div class="yui-g">
                    <!-- YOUR DATA GOES HERE -->
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
        <div class="yui-b">
            <!-- YOUR NAVIGATION GOES HERE -->
            <h1>Tags</h1>
			<ul class="sidemenu">
				<?php echo $this->partialLoop('_partials/sidebar-tags.phtml', $this->getTags()); ?>
			</ul>

			<h1>File Types</h1>
			<ul class="sidemenu">
				<?php echo 'Ext View Helper'; ?>
			</ul>
        </div>
	</div>
    <div id="ft">
            Powered by <a href="http://code.google.com/p/manuscript">Manuscript</a>
    </div>
</div>
</body>
</html>